In [ ]:
import os 
from dotenv import load_dotenv

In [1]:
import pandas as pd

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rupsarroy/heatwave-dataset-rajasthan-india-2006-2025")

data=pd.read_csv(path)

d:\LANG CHAINS\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Malik\.cache\kagglehub\datasets\rupsarroy\heatwave-dataset-rajasthan-india-2006-2025\2.archive...

100%|██████████| 1.34M/1.34M [00:01<00:00, 819kB/s]

Extracting files...

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Malik\\.cache\\kagglehub\\datasets\\rupsarroy\\heatwave-dataset-rajasthan-india-2006-2025\\versions\\2'

In [4]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

In [5]:
data=pd.read_csv(url)

In [6]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
import pandas as pd

# Fetching the latest 50 disaster declarations ($top=50 acts as the limit here)
url = "https://www.fema.gov/api/open/v2/DisasterDeclarationsSummaries?$format=csv&$top=50"
df = pd.read_csv(url)
df.head()

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,iaProgramDeclared,...,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,incidentId,region,designatedIncidentTypes,lastRefresh,hash,id
0,EM-3610-PR,3610,PR,EM,2024-08-13T00:00:00.000Z,2024,Severe Storm,TROPICAL STORM ERNESTO,0,0,...,99001,Adjuntas (Municipio),24124,NaN,2024080901,2,"4,M,W,Z,F",2026-04-27T18:01:29.390Z,ccd089a290654da031dfd82dd3a626b757e6166e,002e8dfc-2a00-49c3-915c-b4cbd2b301b7
1,FM-5529-OR,5529,OR,FM,2024-08-09T00:00:00.000Z,2024,Fire,LEE FALLS FIRE,0,0,...,99067,Washington (County),24122,NaN,2024081001,10,R,2024-08-27T18:22:14.800Z,ae87cf3c6ed795015b714af7166c7c295b2b67c7,09e3f81a-5e16-4b72-b317-1c64e0cfa59c
2,FM-5528-OR,5528,OR,FM,2024-08-06T00:00:00.000Z,2024,Fire,ELK LANE FIRE,0,0,...,99031,Jefferson (County),24116,NaN,2024080701,10,R,2024-08-27T18:22:14.800Z,432cf0995c47e3895cea696ede5621b810460501,59983f89-30bf-4888-b21b-62e8d57d9aac
3,FM-5527-OR,5527,OR,FM,2024-08-02T00:00:00.000Z,2024,Fire,MILE MARKER 132 FIRE,0,0,...,99017,Deschutes (County),24111,NaN,2024080301,10,R,2024-08-27T18:22:14.800Z,2f21d90cb6bc64b0d4121aa3f18d852bbb4b11fa,8d13ecf0-bc2f-496b-8c9f-b2e73da832a0
4,EM-3610-PR,3610,PR,EM,2024-08-13T00:00:00.000Z,2024,Severe Storm,TROPICAL STORM ERNESTO,0,0,...,99003,Aguada (Municipio),24124,NaN,2024080901,2,"4,M,W,Z,F",2026-04-27T18:01:29.390Z,0beaa37210d2cf6c22408616fd69f66339aa81db,ade80f2f-aca5-44b3-a6de-d78e2c8bb58b